FONT_NAME = 'omelette'
FONT_PREFIX = 'om'
FONT_OUTPUT_FOLDER = 'assets'
FONT_SOURCE_FILENAME = 'omelette_source.png'
FONT_COPYRIGHT = 'Copyright (C) 2022 by Andrew G. Crowell. Creative Commons Attribution 4.0 International License (CC BY 4.0).'
FONT_AUTHOR = 'eggboycolor'

CHARACTERS_TO_FONT_PATHNAMES = {
    0x20: 'space',
    0x21: 'exclamation_mark',
    0x22: 'double_quote',
    0x23: 'hash',
    0x24: 'dollar',
    0x25: 'percent',
    0x26: 'ampersand',
    0x27: 'single_quote',
    0x28: 'left_parenthesis',
    0x29: 'right_parenthesis',
    0x2A: 'asterisk',
    0x2B: 'plus',
    0x2C: 'comma',
    0x2D: 'minus',
    0x2E: 'period',
    0x2F: 'slash',
    0x30: 'digit_0',
    0x31: 'digit_1',
    0x32: 'digit_2',
    0x33: 'digit_3',
    0x34: 'digit_4',
    0x35: 'digit_5',
    0x36: 'digit_6',
    0x37: 'digit_7',
    0x38: 'digit_8',
    0x39: 'digit_9',
    0x3A: 'colon',
    0x3B: 'semicolon',
    0x3C: 'less_than',
    0x3D: 'equals',
    0x3E: 'greater_than',
    0x3F: 'question_mark',
    0x40: 'at_sign',
    0x41: 'uppercase_a',
    0x42: 'uppercase_b',
    0x43: 'uppercase_c',
    0x44: 'uppercase_d',
    0x45: 'uppercase_e',
    0x46: 'uppercase_f',
    0x47: 'uppercase_g',
    0x48: 'uppercase_h',
    0x49: 'uppercase_i',
    0x4A: 'uppercase_j',
    0x4B: 'uppercase_k',
    0x4C: 'uppercase_l',
    0x4D: 'uppercase_m',
    0x4E: 'uppercase_n',
    0x4F: 'uppercase_o',
    0x50: 'uppercase_p',
    0x51: 'uppercase_q',
    0x52: 'uppercase_r',
    0x53: 'uppercase_s',
    0x54: 'uppercase_t',
    0x55: 'uppercase_u',
    0x56: 'uppercase_v',
    0x57: 'uppercase_w',
    0x58: 'uppercase_x',
    0x59: 'uppercase_y',
    0x5A: 'uppercase_z',
    0x5B: 'left_bracket',
    0x5C: 'backslash',
    0x5D: 'right_bracket',
    0x5E: 'caret',
    0x5F: 'underscore',
    0x60: 'backquote',
    0x61: 'lowercase_a',
    0x62: 'lowercase_b',
    0x63: 'lowercase_c',
    0x64: 'lowercase_d',
    0x65: 'lowercase_e',
    0x66: 'lowercase_f',
    0x67: 'lowercase_g',
    0x68: 'lowercase_h',
    0x69: 'lowercase_i',
    0x6A: 'lowercase_j',
    0x6B: 'lowercase_k',
    0x6C: 'lowercase_l',
    0x6D: 'lowercase_m',
    0x6E: 'lowercase_n',
    0x6F: 'lowercase_o',
    0x70: 'lowercase_p',
    0x71: 'lowercase_q',
    0x72: 'lowercase_r',
    0x73: 'lowercase_s',
    0x74: 'lowercase_t',
    0x75: 'lowercase_u',
    0x76: 'lowercase_v',
    0x77: 'lowercase_w',
    0x78: 'lowercase_x',
    0x79: 'lowercase_y',
    0x7A: 'lowercase_z',
    0x7B: 'left_brace',
    0x7C: 'vertical_bar',
    0x7D: 'right_brace',
    0x7E: 'tilde',
    0x7F: 'delete',
}

FONT_PATHNAMES_TO_CHARACTERS = {v: k for k, v in CHARACTERS_TO_FONT_PATHNAMES.items()}

FONT_ICON_GLYPH_NAMES = [
    'sword', 'spear', 'shield',
    'staff', 'ring', 'bone',
    'key', 'bag', 'egg',
    'armor', 'full_heart', 'half_heart',
    'empty_heart', 'full_bottle', 'empty_bottle',
    'full_star', 'empty_star', 'light_orb',
    'dark_orb', 'diamond', 'heart',
    'spade', 'club', 'floppy',
    'mouse_cursor', 'folder', 'left_arrow',
    'right_arrow', 'up_arrow', 'down_arrow',
    'checkmark', 'o', 'axe',
    'whip', 'boot', 'glove',
    'tree', 'envelope', 'book',
    'scroll', 'vegetable', 'meat',
    'fish', 'fruit', 'burger',
    'paw', 'music_note', 'flame',
    'droplet', 'snowflake', 'tornado',
    'snowman', 'lightning', 'firework',
    'slime', 'bubbles', 'hourglass',
    'document', 'sparkles', 'pillar',
    'home', 'building', 'factory',
    'x',
]

FONT_WINDOW_GLYPH_NAMES = [
    'border_tl', 'border_tm', 'border_tr',
    'fill_tl', 'fill_tm', 'fill_tr',
    'cursor_tl', 'cursor_tr', 'border_ml',
    'dashed_box', 'border_mr', 'fill_ml',
    'fill_mm', 'fill_mr', 'cursor_bl',
    'cursor_br', 'border_bl', 'border_bm',
    'border_br', 'fill_bl', 'fill_bm',
    'fill_br', 'smile', 'frown',
]

FONT_ICON_MAPPINGS = {
    'window': [ord(i) for i in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'],
    'buttons': [i for i in range(32, 128)],
    'icons': [ord(i) for i in 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@'],
}